# Generated by Django 5.0.7 on 2026-08-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(upload_to='packages/')),
                ('status', models.CharField(choices=[('pending', 'Awaiting pickup'), ('picked_up', 'Picked up')], default='pending', max_length=20)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_by', models.CharField(blank=True, help_text='Name of who collected the package', max_length=150)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
