# Generated by Django 5.0.7 on 2026-08-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='providers/evidence/before/')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='providers/evidence/after/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Evidences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('contract_number', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='providers/documents/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
